// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: LED

#include "../ui.h"

void ui_Index_screen_init(void)
{
    ui_Index = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Index, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qrcode_body = lv_obj_create(ui_Index);
    lv_obj_set_width(ui_qrcode_body, 200);
    lv_obj_set_height(ui_qrcode_body, 200);
    lv_obj_set_x(ui_qrcode_body, -113);
    lv_obj_set_y(ui_qrcode_body, -3);
    lv_obj_set_align(ui_qrcode_body, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_qrcode_body, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_qrcode_body, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Index);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 123);
    lv_obj_set_y(ui_Label1, -80);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Ahoy!");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x38DB37), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Index);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 123);
    lv_obj_set_y(ui_Label2, 48);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Let get in");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cname = lv_label_create(ui_Index);
    lv_obj_set_width(ui_cname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cname, 94);
    lv_obj_set_y(ui_cname, -15);
    lv_obj_set_align(ui_cname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cname, "name");
    lv_obj_set_style_text_font(ui_cname, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btncheck = lv_btn_create(ui_Index);
    lv_obj_set_width(ui_btncheck, 100);
    lv_obj_set_height(ui_btncheck, 37);
    lv_obj_set_x(ui_btncheck, 94);
    lv_obj_set_y(ui_btncheck, 103);
    lv_obj_set_align(ui_btncheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btncheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btncheck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_btncheck);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "open");

}
